#ifndef CONFIG_APP_H
#define CONFIG_APP_H

#define LED_NODE   DT_ALIAS(led0)
#define BTN_NODE   DT_ALIAS(sw0)

#define THREAD_A_STACK_SIZE   1024
#define THREAD_B_STACK_SIZE   1024
#define THREAD_PRIORITY       K_PRIO_PREEMPT(1)

#define UART_RX_RINGBUF_SIZE  256
#define UART_TX_RINGBUF_SIZE  256

#define UART_RX_BUFFER_SIZE 64

#define UART_RX_THREAD_STACK_SIZE 1024
#define UART_RX_THREAD_PRIORITY K_PRIO_PREEMPT(2)

#endif